In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [38]:
df=pd.read_csv("Algerian_forest_fires_dataset.csv")

In [39]:
import pandas as pd
from ydata_profiling import ProfileReport

# 1. Replace 'your_file.csv' with your actual filename or full path
df = pd.read_csv("Algerian_forest_fires_dataset.csv")

# 2. Generate and save the report
profile = ProfileReport(df, title="My Dataset Report", explorative=True)
profile.to_file("my_data_analysis.html")

print("Done! Open 'my_data_analysis.html' in your browser.")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 14/14 [00:00<00:00, 72.34it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

Done! Open 'my_data_analysis.html' in your browser.

In [40]:
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          246 non-null    object
 1   month        245 non-null    object
 2   year         245 non-null    object
 3   Temperature  245 non-null    object
 4    RH          245 non-null    object
 5    Ws          245 non-null    object
 6   Rain         245 non-null    object
 7   FFMC         245 non-null    object
 8   DMC          245 non-null    object
 9   DC           245 non-null    object
 10  ISI          245 non-null    object
 11  BUI          245 non-null    object
 12  FWI          245 non-null    object
 13  Classes      244 non-null    object
dtypes: object(14)
memory usage: 27.1+ KB

In [42]:
df.isna().sum()
df.dropna(inplace=True)

In [43]:
df.isna().sum()

day            0
month          0
year           0
Temperature    0
 RH            0
 Ws            0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
dtype: int64

In [44]:
df.duplicated().sum()

np.int64(0)

In [45]:
df.shape

(244, 14)

In [46]:
df.rename(columns={" RH":"RH"," Ws":"Ws","Classes  ":"Classes","Rain ":"Rain"},inplace=True)

In [47]:
df=df[df["day"]!="day"]

In [48]:
num_cols=["day","month","year","Temperature","RH","Ws"]
df[num_cols]=df[num_cols].astype("int64")

In [49]:
float_cols=df.columns[6:13]
df[float_cols]=df[float_cols].astype("float")

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 246
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    int64
 1   month        243 non-null    int64
 2   year         243 non-null    int64
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    int64
 6   Rain         243 non-null    float64
 7   FFMC         243 non-null    float64
 8   DMC          243 non-null    float64
 9   DC           243 non-null    float64
 10  ISI          243 non-null    float64
 11  BUI          243 non-null    float64
 12  FWI          243 non-null    float64
 13  Classes      243 non-null    object
dtypes: float64(7), int64(6), object(1)
memory usage: 28.5+ KB

In [51]:
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes'],
      dtype='object')

In [52]:
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,1,6,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,not fire
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,not fire
4,5,6,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire

In [53]:
num_cols.extend(float_cols)
full_cols=num_cols

In [54]:
fig,ax=plt.subplots(7,2,figsize=(8,20))
for i,cols in enumerate(full_cols):
    sns.histplot(data=df,x=cols,ax=ax[i//2,i%2])
plt.tight_layout()
plt.show()

In [55]:
corr=df[full_cols].corr()
plt.figure(figsize=(15,11))
sns.heatmap(corr,annot=True)

In [56]:
df["Classes"]=df["Classes"].str.strip()

In [57]:
df=df.drop(columns=["month","Ws","year","day"])

In [58]:
df.head()

   Temperature  RH  Rain  FFMC  DMC    DC  ISI  BUI  FWI   Classes
0           29  57   0.0  65.7  3.4   7.6  1.3  3.4  0.5  not fire
1           29  61   1.3  64.4  4.1   7.6  1.0  3.9  0.4  not fire
2           26  82  13.1  47.1  2.5   7.1  0.3  2.7  0.1  not fire
3           25  89   2.5  28.6  1.3   6.9  0.0  1.7  0.0  not fire
4           27  77   0.0  64.8  3.0  14.2  1.2  3.9  0.5  not fire

In [59]:
df["Classes"]=df["Classes"].map({"not fire":0,"fire":1})

In [60]:
df

     Temperature  RH  Rain  FFMC   DMC    DC  ISI   BUI  FWI  Classes
0             29  57   0.0  65.7   3.4   7.6  1.3   3.4  0.5        0
1             29  61   1.3  64.4   4.1   7.6  1.0   3.9  0.4        0
2             26  82  13.1  47.1   2.5   7.1  0.3   2.7  0.1        0
3             25  89   2.5  28.6   1.3   6.9  0.0   1.7  0.0        0
4             27  77   0.0  64.8   3.0  14.2  1.2   3.9  0.5        0
..           ...  ..   ...   ...   ...   ...  ...   ...  ...      ...
242           30  65   0.0  85.4  16.0  44.5  4.5  16.9  6.5        1
243           28  87   4.4  41.1   6.5   8.0  0.1   6.2  0.0        0
244           27  87   0.5  45.9   3.5   7.9  0.4   3.4  0.2        0
245           24  54   0.1  79.7   4.3  15.2  1.7   5.1  0.7        0
246           24  64   0.2  67.3   3.8  16.5  1.2   4.8  0.5        0

[243 rows x 10 columns]

In [61]:
df[["FWI", "Classes"]].corr()

              FWI   Classes
FWI      1.000000  0.719216
Classes  0.719216  1.000000

In [62]:
sns.boxplot(x="Classes", y="FWI", data=df)

In [63]:

df.hist(bins=50,figsize=(15,20))
plt.show()

In [64]:
df=df.drop("BUI",axis=1)

In [65]:
df.to_csv("Algerian_forest_cleanded_dataset.csv",index=None)

In [66]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split,GridSearchCV,cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

X=df.drop("FWI",axis=1)
y=df["FWI"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


pipeline=Pipeline([
    ("scaler",StandardScaler()),
    ("model",Lasso())
])

param_grid = {
    "model__alpha": [0.001, 0.01, 0.1, 1],
    "model__fit_intercept": [True, False],
    "model__max_iter": [1000, 5000],
    "model__tol": [1e-4, 1e-3],
    "model__selection": ["cyclic", "random"],
    "model__positive": [True, False]
}

grid=GridSearchCV(
    pipeline,
    param_grid=param_grid,
    cv=5,
    n_jobs=-1,
)

grid.fit(X_train,y_train)

print(grid.best_score_)

print("best-params--:",grid.best_params_)

best_model=grid.best_estimator_

y_pred=best_model.predict(X_test)

print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

0.9561799884298715
best-params--: {'model__alpha': 0.1, 'model__fit_intercept': True, 'model__max_iter': 1000, 'model__positive': False, 'model__selection': 'random', 'model__tol': 0.001}
0.9688832266018609
0.6098057804639103
0.9431002835921496

In [67]:
sns.scatterplot(x=y_test,y=y_pred)

In [68]:
corr=X_train.corr()
plt.figure(figsize=(12,8))
sns.heatmap(corr,annot=True)

In [69]:
# import numpy as np

# # Correlation matrix
# corr_matrix = df.corr(numeric_only=True).abs()

# # Upper triangle
# upper = corr_matrix.where(
#     np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
# )

# # Features to drop
# threshold = 0.90
# to_drop = [col for col in upper.columns if any(upper[col] > threshold)]

# print("Columns to drop:", to_drop)

# # Drop columns
# df = df.drop(columns=to_drop)

# print(df.head())

In [72]:
import joblib

joblib.dump(best_model,"best_model.joblib")

['best_model.joblib']